### ISSUE TITLE
🚀 Improvements tracker

### ISSUE THREAD

**Issue by NikolaLohinski** [NikolaLohinski/gonja#3]
Hi there !

If you are interested in one of the improvements listed below, please react to the comment with 👍 so I can prioritize it.

If you have other feature requests, feel free to add an item in this issue or open a new one if you feel a discussion might be better, and I'll add it here afterwards.

Thanks 🙏

<details>
  <summary>Click me to see finished work</summary>

# 🚀 Features
- [x] Support inline if/else conditions: `{{ ... if ... else ... }}`
  
  Done in [`v1.4.0`](https://github.com/NikolaLohinski/gonja/tree/v1.4.0)
- [x] https://github.com/noirbizarre/gonja/issues/4
  
  Done in [`v1.3.5`](https://github.com/NikolaLohinski/gonja/tree/v1.3.5)

- [x] Add a `match` filte to be able to match against regular expressions
  
  Done in [`v1.5.0`](https://github.com/NikolaLohinski/gonja/tree/v1.5.0)

- [x] Use ginkgo and gomega for unit testing
  
  Done in [`v2.0.0`](https://github.com/NikolaLohinski/gonja/tree/v2.0.0)

- [x] Support trailing line stripping from the config
  
  Done in [`v2.0.0`](https://github.com/NikolaLohinski/gonja/tree/v2.0.0)

- [x] Support block stripping from the config and block stripping disabling with {%+ ... +%} (cf. https://jinja.palletsprojects.com/en/3.0.x/templates/#whitespace-control)
  
  Done in [`v2.0.0`](https://github.com/NikolaLohinski/gonja/tree/v2.0.0)

- [x] Implement a CI with github actions

  Done in [`v2.1.2`](https://github.com/NikolaLohinski/gonja/tree/v2.1.2)
# 🐛 Bug fixes
- [x] the `default` filter is not compliant with Python implementation when it comes to handling boolean false values
  
  Fixed in [`v1.3.4`](https://github.com/NikolaLohinski/gonja/tree/v1.3.4)
- [x] `https://github.com/NikolaLohinski/terraform-provider-jinja/issues/8
  
   Fixed in [`v1.3.4`](https://github.com/NikolaLohinski/gonja/tree/v1.3.4)
- [x] https://github.com/noirbizarre/gonja/issues/10
  
  Fixed in [`v1.4.1`](https://github.com/NikolaLohinski/gonja/tree/v1.4.1)

- [x] using `...[...]` object access panics if the key is missing. It should throw an error instead

  Fixed in [`v1.4.2`](https://github.com/NikolaLohinski/gonja/tree/v1.4.2)

- [x] `{% if ... %} ... {% endif #}` makes the engine panic 

  Fixed in [`v1.5.1`](https://github.com/NikolaLohinski/gonja/tree/v1.5.1)

- [x] using the `sort` filter on an empty list panics

  Fixed in [`v1.5.1`](https://github.com/NikolaLohinski/gonja/tree/v1.5.1)

- [x] Two consecutive dots .. in a variable block lead to panic
  
  Fixed in [`v2.0.0`](https://github.com/NikolaLohinski/gonja/tree/v2.0.0)
</details>

**Comment by NikolaLohinski** [comment]
- [ ] Support inline if/else conditions: `{{ ... if ... else ... }}`

**Comment by NikolaLohinski** [comment]
- [ ] Support multi arguments tests : `{{ if ... is ... and/or ... }}`

**Comment by NikolaLohinski** [comment]
- [ ] Create a `merge` filter to do dynamic deep merging of dicts

**Comment by NikolaLohinski** [comment]
- [ ] Support trailing line stripping from the config

**Comment by NikolaLohinski** [comment]
- [ ] Support block stripping from the config and block stripping disabling with `{%+ ... +%}` (cf. https://jinja.palletsprojects.com/en/3.0.x/templates/#whitespace-control)

**Comment by NikolaLohinski** [comment]
- [ ] the ˋdefault` filter is not compliant with Python implementation when it comes to handling boolean false values

**Comment by NikolaLohinski** [comment]
- [ ] Use `ginkgo` and `gomega` for unit testing

**Comment by NikolaLohinski** [comment]
- [ ] Create a global function called `file` similiar to the `file` filter

**Comment by NikolaLohinski** [comment]
- [ ] Implement a CI with github actions

**Comment by NikolaLohinski** [comment]
- [ ] Improve/clean godoc

**Comment by NikolaLohinski** [comment]
- [ ] https://github.com/noirbizarre/gonja/issues/10

**Comment by NikolaLohinski** [comment]
- [ ] implement the `%` operator for the `format` flter as depicted in https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.format

**Comment by NikolaLohinski** [comment]
- [] `{% if ... %} ... {% endif #}` makes the engine panic

**Comment by NikolaLohinski** [comment]
- [ ] using the `sort` filter on an empty list panics

**Comment by NikolaLohinski** [comment]
- [ ] Two consecutive dots `..` in a variable block lead to panic

**Comment by NikolaLohinski** [comment]
Closing as project is is maintenance mode unless new feature requests are made
